# Generated by Django 3.2.1 on 2021-05-05 10:30

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('physics', 'Physics'), ('maths', 'Maths'), ('ct', 'CT'), ('c', 'C'), ('fit', 'FIT'), ('pst', 'PST')], max_length=8),
        ),
    ]
