# Generated by Django 3.2.2 on 2021-05-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210505_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/'),
        ),
    ]
